#!/bin/bash

DIR="$( cd "$( dirname "$0" )" && pwd )"

main() {
    FILES=$(ls -a $DIR/files/ --ignore='.' --ignore='..');

    for FILE in $FILES
    do
        rm -rf $HOME/$FILE
        ln -s  $FOLDER/files/$FILE $HOME/$FILE
    done
    echo "Symbolic links created to the home directory"
}

main

:
